<?php

namespace DoctrineProxies\__CG__;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EMeal extends \EMeal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EMeal' . "\0" . 'idMeal', '' . "\0" . 'EMeal' . "\0" . 'nameMeal', '' . "\0" . 'EMeal' . "\0" . 'imageMeal', '' . "\0" . 'EMeal' . "\0" . 'type', '' . "\0" . 'EMeal' . "\0" . 'recipe', '' . "\0" . 'EMeal' . "\0" . 'servings', '' . "\0" . 'EMeal' . "\0" . 'mealPlan'];
        }

        return ['__isInitialized__', '' . "\0" . 'EMeal' . "\0" . 'idMeal', '' . "\0" . 'EMeal' . "\0" . 'nameMeal', '' . "\0" . 'EMeal' . "\0" . 'imageMeal', '' . "\0" . 'EMeal' . "\0" . 'type', '' . "\0" . 'EMeal' . "\0" . 'recipe', '' . "\0" . 'EMeal' . "\0" . 'servings', '' . "\0" . 'EMeal' . "\0" . 'mealPlan'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EMeal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMeal(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdMeal();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMeal', []);

        return parent::getIdMeal();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameMeal(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameMeal', []);

        return parent::getNameMeal();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageMeal(): \EImage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageMeal', []);

        return parent::getImageMeal();
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipe(): ?\ERecipe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipe', []);

        return parent::getRecipe();
    }

    /**
     * {@inheritDoc}
     */
    public function getServings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServings', []);

        return parent::getServings();
    }

    /**
     * {@inheritDoc}
     */
    public function getMealPlan(): ?\EMealPlan
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMealPlan', []);

        return parent::getMealPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameMeal(string $nameMeal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameMeal', [$nameMeal]);

        parent::setNameMeal($nameMeal);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageMeal(\EImage $imageMeal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageMeal', [$imageMeal]);

        parent::setImageMeal($imageMeal);
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipe(\ERecipe $recipe): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipe', [$recipe]);

        parent::setRecipe($recipe);
    }

    /**
     * {@inheritDoc}
     */
    public function setMealPlan(?\EMealPlan $mealPlan): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMealPlan', [$mealPlan]);

        parent::setMealPlan($mealPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function addServing(\EServing $serving): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServing', [$serving]);

        parent::addServing($serving);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServing(\EServing $serving): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServing', [$serving]);

        parent::removeServing($serving);
    }

}
