<?php

namespace DoctrineProxies\__CG__;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EServing extends \EServing implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EServing' . "\0" . 'idServing', '' . "\0" . 'EServing' . "\0" . 'description', '' . "\0" . 'EServing' . "\0" . 'calories', '' . "\0" . 'EServing' . "\0" . 'carbohydrate', '' . "\0" . 'EServing' . "\0" . 'protein', '' . "\0" . 'EServing' . "\0" . 'fat', '' . "\0" . 'EServing' . "\0" . 'meal'];
        }

        return ['__isInitialized__', '' . "\0" . 'EServing' . "\0" . 'idServing', '' . "\0" . 'EServing' . "\0" . 'description', '' . "\0" . 'EServing' . "\0" . 'calories', '' . "\0" . 'EServing' . "\0" . 'carbohydrate', '' . "\0" . 'EServing' . "\0" . 'protein', '' . "\0" . 'EServing' . "\0" . 'fat', '' . "\0" . 'EServing' . "\0" . 'meal'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EServing $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdServing(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdServing();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdServing', []);

        return parent::getIdServing();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getCalories(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalories', []);

        return parent::getCalories();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarbohydrate(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarbohydrate', []);

        return parent::getCarbohydrate();
    }

    /**
     * {@inheritDoc}
     */
    public function getProtein(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtein', []);

        return parent::getProtein();
    }

    /**
     * {@inheritDoc}
     */
    public function getFat(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFat', []);

        return parent::getFat();
    }

    /**
     * {@inheritDoc}
     */
    public function getMeal(): ?\EMeal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeal', []);

        return parent::getMeal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setCalories(float $calories): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalories', [$calories]);

        parent::setCalories($calories);
    }

    /**
     * {@inheritDoc}
     */
    public function setCarbohydrate(float $carbohydrate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarbohydrate', [$carbohydrate]);

        parent::setCarbohydrate($carbohydrate);
    }

    /**
     * {@inheritDoc}
     */
    public function setProtein(float $protein): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtein', [$protein]);

        parent::setProtein($protein);
    }

    /**
     * {@inheritDoc}
     */
    public function setFat(float $fat): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFat', [$fat]);

        parent::setFat($fat);
    }

    /**
     * {@inheritDoc}
     */
    public function setMeal(?\EMeal $meal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeal', [$meal]);

        parent::setMeal($meal);
    }

}
