<?php

namespace DoctrineProxies\__CG__;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EMealPlan extends \EMealPlan implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EMealPlan' . "\0" . 'idMealPlan', '' . "\0" . 'EMealPlan' . "\0" . 'nameMealPlan', '' . "\0" . 'EMealPlan' . "\0" . 'description', '' . "\0" . 'EMealPlan' . "\0" . 'tag', '' . "\0" . 'EMealPlan' . "\0" . 'creator', '' . "\0" . 'EMealPlan' . "\0" . 'creation_time', '' . "\0" . 'EMealPlan' . "\0" . 'recipes', '' . "\0" . 'EMealPlan' . "\0" . 'meals'];
        }

        return ['__isInitialized__', '' . "\0" . 'EMealPlan' . "\0" . 'idMealPlan', '' . "\0" . 'EMealPlan' . "\0" . 'nameMealPlan', '' . "\0" . 'EMealPlan' . "\0" . 'description', '' . "\0" . 'EMealPlan' . "\0" . 'tag', '' . "\0" . 'EMealPlan' . "\0" . 'creator', '' . "\0" . 'EMealPlan' . "\0" . 'creation_time', '' . "\0" . 'EMealPlan' . "\0" . 'recipes', '' . "\0" . 'EMealPlan' . "\0" . 'meals'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EMealPlan $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMealPlan(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdMealPlan();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMealPlan', []);

        return parent::getIdMealPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameMealPlan(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameMealPlan', []);

        return parent::getNameMealPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getTag(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag', []);

        return parent::getTag();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator(): \EProfile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', []);

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationTime(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationTime', []);

        return parent::getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeStr(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeStr', []);

        return parent::getTimeStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipes', []);

        return parent::getRecipes();
    }

    /**
     * {@inheritDoc}
     */
    public function getMeals(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeals', []);

        return parent::getMeals();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameMealPlan(string $nameMealPlan): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameMealPlan', [$nameMealPlan]);

        parent::setNameMealPlan($nameMealPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setTag(string $tag): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag', [$tag]);

        parent::setTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\EProfile $creator): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', [$creator]);

        parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationTime(\DateTime $dateTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationTime', [$dateTime]);

        parent::setCreationTime($dateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function addRecipe(\ERecipe $recipe): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecipe', [$recipe]);

        parent::addRecipe($recipe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecipe(\ERecipe $recipe): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecipe', [$recipe]);

        parent::removeRecipe($recipe);
    }

    /**
     * {@inheritDoc}
     */
    public function addMeal(\EMeal $meal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMeal', [$meal]);

        parent::addMeal($meal);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMeal(\EMeal $meal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMeal', [$meal]);

        parent::removeMeal($meal);
    }

}
